name: my_data_lab
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.8.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h06df861_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - bleach=6.2.0=pyhd8ed1ab_3
  - bleach-with-css=6.2.0=hd8ed1ab_3
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py39hfa9831e_2
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - catalogue=2.0.10=py39h2804cbe_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h7f933ea_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - cloudpathlib=0.20.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - confection=0.1.4=py39h766bdb0_0
  - contourpy=1.3.0=py39h85b62ae_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.10=py39h941272d_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - cython-blis=1.0.1=py39hae3cbf7_0
  - debugpy=1.8.11=py39h941272d_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fonttools=4.55.3=py39hefdd603_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hadb7bae_2
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - greenlet=3.2.4=py39h2769f79_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipywidgets=7.8.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39h2804cbe_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab-git=0.50.2=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=1.1.11=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h157d57c_0
  - krb5=1.21.3=h237132a_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=26_osxarm64_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=26_osxarm64_openblas
  - libcxx=19.1.6=ha82da77_1
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20240808=pl5321hafb1f1b_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=26_osxarm64_openblas
  - liblzma=5.6.3=h39f12f2_1
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.28=openmp_hf332438_1
  - libpng=1.6.45=h3783ad8_0
  - libpq=17.7=h944245b_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.47.2=h3f77e49_0
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.6=hdb05f8b_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39hefdd603_1
  - matplotlib=3.9.4=py39hdf13c20_0
  - matplotlib-base=3.9.4=py39h7251d6c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.10=py39h3e40a14_2
  - nbclassic=1.2.0=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.5=pyhd8ed1ab_1
  - nbdime=4.0.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.0.2=py39h3ba1154_1
  - openjpeg=2.5.3=h8a3d83b_0
  - openldap=2.6.10=hbe55e7a_0
  - openpyxl=3.1.5=py39h5f73de6_1
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39hc5ad87a_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39hfea3036_0
  - pip=24.3.1=pyh8b19718_2
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=5.24.1=pyhd8ed1ab_1
  - preshed=3.0.9=py39h3e40a14_2
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py39hf3bc14e_0
  - psycopg2=2.9.10=py39hccd8f27_1
  - psycopg2-binary=2.9.10=pyhd8ed1ab_1
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.5=pyh3cfb1c2_0
  - pydantic-core=2.27.2=py39hc40b5db_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyobjc-core=10.3.2=py39hebff0d6_0
  - pyobjc-framework-cocoa=10.3.2=py39hebff0d6_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.21=h5f1b60f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h06df861_1
  - pyzmq=26.2.0=py39h6e893d0_3
  - qgrid=1.3.1=pyhd8ed1ab_5
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.22.3=py39hc40b5db_0
  - scikit-learn=1.6.1=py39h451895d_0
  - scipy=1.13.1=py39h3d5391c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=75.8.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - smart-open=7.1.0=hd8ed1ab_0
  - smart_open=7.1.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spacy=3.8.2=py39h7d68603_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlalchemy=2.0.43=py39he7485ab_0
  - srsly=2.4.8=py39hb198ff7_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py39h914ef23_0
  - tenacity=9.0.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - thinc=8.3.2=py39h7d68603_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39hf3bc14e_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.15.1=pyhd8ed1ab_0
  - typer-slim=0.15.1=pyhd8ed1ab_0
  - typer-slim-standard=0.15.1=hd8ed1ab_0
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py39h57695bc_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vincent=0.4.4=py_1
  - wasabi=1.1.2=py39h2804cbe_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - weasel=0.4.1=pyhd8ed1ab_2
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=3.6.10=pyhd8ed1ab_0
  - wrapt=1.17.0=py39hf3bc14e_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py39hcf1bb16_1
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - cachetools==6.2.4
      - distro==1.9.0
      - en-core-web-sm==3.8.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-genai==1.47.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - httplib2==0.31.0
      - jiter==0.12.0
      - jupyter-contrib-core==0.4.2
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.4
      - kagglehub==0.3.12
      - lxml==6.0.1
      - openai==2.14.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - python-dotenv==1.2.1
      - rsa==4.9.1
      - uritemplate==4.2.0
      - websockets==15.0.1
prefix: /opt/anaconda3/envs/my_data_lab
